Repository pycontribs/tendo, pull requests merged in 2022-10, with the labels that each got.

#58 feat: refactor singleton to use context manager
  CHANGELOG.md
  LICENSE.md
  LICENSE.txt
  requirements-dev.txt
  setup.cfg
  setup.py
  tendo/__init__.py
  tendo/singleton.py
  tendo/tests/test_colorer.py
  tendo/tests/test_singleton.py
Labels: enhancement

#59 Refresh GHA configuration
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: skip-changelog

#63 Refresh GHA setup part 2
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/tox.yml
  README.rst
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: skip-changelog

#65 Replace pbr with setuptools
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  MANIFEST.in
  Makefile
  README.rst
  codecov.yml
  pyproject.toml
  pytest.ini
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
  src/tendo/__init__.py
  src/tendo/ansiterm.py
  src/tendo/colorer.py
  src/tendo/execfile2.py
  src/tendo/py.typed
  src/tendo/singleton.py
  src/tendo/tee.py
  src/tendo/tests/__init__.py
  src/tendo/tests/assets/full_sample_utf8_bom.txt
  src/tendo/tests/assets/sample_ucs2_be.txt
  src/tendo/tests/assets/sample_ucs2_le.txt
  src/tendo/tests/assets/sample_utf8.txt
  src/tendo/tests/assets/sample_utf8_bom.txt
  src/tendo/tests/assets/utf8-after-append.txt
  src/tendo/tests/assets/utf8-invalid.txt
  src/tendo/tests/assets/utf8.txt
  src/tendo/tests/py.typed
  src/tendo/tests/test_colorer.py
  src/tendo/tests/test_execfile2.py
  src/tendo/tests/test_singleton.py
  src/tendo/tests/test_tee.py
  src/tendo/tests/test_unicode.py
  src/tendo/unicode.py
  tox.ini
Labels: enhancement, skip-changelog

#67 More cleaning
  CHANGES.txt
  LICENSE
  clean.sh
  setup.cfg
  src/tendo/__init__.py
Labels: bug, skip-changelog

#68 Convert readme to markdown
  README.md
  README.rst
  setup.cfg
Labels: bug

#69 GHA fixes
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#71 refactor: singleton is now a context manager
  src/tendo/singleton.py
  src/tendo/tests/test_singleton.py
Labels: enhancement

#75 Enable black
  .pre-commit-config.yaml
  demo/demo_colorer.py
  docs/conf.py
  docs/make.py
  setup.cfg
  src/tendo/__init__.py
  src/tendo/ansiterm.py
  src/tendo/colorer.py
  src/tendo/execfile2.py
  src/tendo/singleton.py
  src/tendo/tee.py
  src/tendo/tests/test_colorer.py
  src/tendo/tests/test_execfile2.py
  src/tendo/tests/test_singleton.py
  src/tendo/tests/test_tee.py
  src/tendo/tests/test_unicode.py
  src/tendo/unicode.py
Labels: bug
