Repository pycontribs/tendo, pull requests merged in 2024-11, with the labels that each got.

#95 Adopt reusable tox workflow
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#96 Enable support for python 3.13 and 3.13
  .github/workflows/tox.yml
  .gitignore
  pyproject.toml
  setup.cfg
  src/tendo/tee.py
  tox.ini
Labels: bug

#90 Fix documentation links
  README.md
Labels: bug

#97 Require python3.10 or newer
  setup.cfg
Labels: major

#100 Adopt ruff
  .pre-commit-config.yaml
  demo/demo_colorer.py
  pyproject.toml
  setup.cfg
  src/tendo/__init__.py
  src/tendo/ansiterm.py
  src/tendo/colorer.py
  src/tendo/execfile2.py
  src/tendo/singleton.py
  src/tendo/tee.py
  src/tendo/tests/test_singleton.py
  src/tendo/tests/test_tee.py
  src/tendo/tests/test_unicode.py
  src/tendo/unicode.py
Labels: bug

#101 Fix GHA pipelines
  .github/workflows/ack.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#102 Give permission to update releases
  .github/workflows/tox.yml
Labels: skip-changelog

#105 Removed colorer and ansiterm modules
  README.md
  demo/demo_colorer.py
  pyproject.toml
  src/tendo/__init__.py
  src/tendo/ansiterm.py
  src/tendo/colorer.py
  src/tendo/tee.py
  src/tendo/tests/test_colorer.py
  tox.ini
Labels: major

#106 Remove support for Windows
  README.md
  pyproject.toml
  src/tendo/singleton.py
  src/tendo/tee.py
  src/tendo/tests/test_tee.py
Labels: major
